appearance:
  mode: system
  color: emerald

marketing:
  seo:
    site_type: Person
    description: Ethan Feilich's Personal Website

header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Ethan Feilich"

footer:
  copyright:
    notice: '© {year} Ethan Feilich. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
i_am_a_sponsor: true

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  math:
    enable: false
  privacy_pack:
    enable: false